### ISSUE TITLE
Moving hose above tank in Fluid Pressure and Flow breaks Water tower screen

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/decaf#100] opened 2020-04-27 22:42 UTC
<b>Test Device</b>

Windows 10 Laptop

<b>Operating System</b>

Windows 10 1903

<b>Browser</b>

Edge 81.0.416.64 

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/499

On the Water Tank screen, if the hose is raised above the tank a white box obscuring the screen appears. Switching away from the screen and back results in a completely blank screen. This behavior is not present in Java.

<b>Steps to Reproduce</b>

1. Switch to Water Tank screen
2. Check the Hose box
3. Move the hose above the tank using the yellow handle located near the bottom of the screen

<b>Visuals</b>

![2020-04-27DecafFlowEdgeProper](https://user-images.githubusercontent.com/54685448/80427995-1d8dc380-88a6-11ea-8189-0220bd902b0e.gif)

**Comment by lmulhall-phet** [comment] 2020-04-28 21:24
This is a duplicate of https://github.com/phetsims/decaf/issues/81.

**Comment by samreid** [comment] 2020-05-12 03:57
Closing as duplicate, thanks!

**Closed by samreid** 2020-05-12 03:57 UTC
Labels: type:bug, type:duplicate
