### ISSUE TITLE
Individual sims of Motion Series fail to load

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/decaf#23] opened 2020-04-01 21:33 UTC
For https://github.com/phetsims/QA/issues/489
https://phet-dev.colorado.edu/decaf/motion-series/1.0.0-dev.2/

Issues appears on Windows FireFox.
The individual sims within motion series fail to load, while the option menu for selecting sims does load. When tested using a higher performance PC sims still fail to load

![2020-04-01DecafMotionseries](https://user-images.githubusercontent.com/54685448/78188206-11d8e980-742d-11ea-89fe-147166c6a6b5.gif)

**Comment by loganbraywork** [comment] 2020-04-02 21:17
The console log and errors are as follows:

CheerpJ is initializing loader.js:2838:11
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:283
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:95
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
Reporting error: Script error. loader.js:3054:10
ReferenceError: _c4pbM_8nG1uocdGbrnTidabrkDjsqD9ueqJuHteZMONn is not defined rt.jar.sun.awt.image.js:466:4061
    _c4pbM_8nG1uocdGbrnTidabr2CjsGEbYYerKxnn https://cjrtnc.leaningtech.com/2.1/runtime/rt.jar.sun.awt.image.js:466
    _h4V53awt5image17AffineTransformOp6filterE3 https://cjrtnc.leaningtech.com/2.1/runtime/rt.jar.java.awt.image.js:62
    _c4_23edu8colorado4phet6common10eXGrlumEfcHvbOkj2BufferedImageUtils15getRe8ZrviS3o https://phet-dev.colorado.edu/decaf/motion-series/1.0.0-dev.2/motion-series_all.jar.js:7174
    anonymous https://cjrtnc.leaningtech.com/2.1/loader.js line 115 > Function:3
    runContinuationStack https://cjrtnc.leaningtech.com/2.1/loader.js:387
    cheerpjSchedule https://cjrtnc.leaningtech.com/2.1/loader.js:1110
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by samreid** [comment] 2020-04-06 14:47
Caused by #9, tracking there, closing.

**Closed by samreid** 2020-04-06 14:47 UTC
Labels: type:bug
