### ISSUE TITLE
Reactions & Rates fails to load

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/decaf#22] opened 2020-04-01 21:08 UTC
For https://github.com/phetsims/QA/issues/489
https://phet-dev.colorado.edu/decaf/reactions-and-rates/1.0.0-dev.2/

Reactions & Rates fails to load on Windows Firefox, Chrome, & Edge. When tested on a higher performance PC the sim still fails to load.

![2020-04-01DecafReactions Rates](https://user-images.githubusercontent.com/54685448/78186803-970ecf00-742a-11ea-9d33-5d9941795482.gif)

**Comment by loganbraywork** [comment] 2020-04-02 21:20
The console and error log for Windows Firefox are as follows:

CheerpJ is initializing loader.js:2838:11
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:7:19
Reporting error: Script error. loader.js:3054:10
ReferenceError: _c4pbM_8nG1uocdGbrnTidabrkDjsqD9ueqJuHteZMONn is not defined rt.jar.sun.awt.image.js:466:4061
    _c4pbM_8nG1uocdGbrnTidabr2CjsGEbYYerKxnn https://cjrtnc.leaningtech.com/2.1/runtime/rt.jar.sun.awt.image.js:466
    _h4V53awt5image17AffineTransformOp6filterE3 https://cjrtnc.leaningtech.com/2.1/runtime/rt.jar.java.awt.image.js:62
    _c4V33edu8colorado4phet6common11piceHbrtuaQnADQidGbXhGWKteMUqebWeHNn https://phet-dev.colorado.edu/decaf/reactions-and-rates/1.0.0-dev.2/reactions-and-rates_all.jar.js:3239
    anonymous https://cjrtnc.leaningtech.com/2.1/loader.js line 115 > Function:3
    runContinuationStack https://cjrtnc.leaningtech.com/2.1/loader.js:387
    cheerpjSchedule https://cjrtnc.leaningtech.com/2.1/loader.js:1110
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by samreid** [comment] 2020-04-06 14:45
Caused by #9, tracking there, closing.

**Closed by samreid** 2020-04-06 14:45 UTC
Labels: type:bug
