### ISSUE TITLE
Individual sims in Optical Tweezers fail to load

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/decaf#25] opened 2020-04-01 22:40 UTC
For https://github.com/phetsims/QA/issues/489
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.3/

Molecular Motors, Optical Tweezers and Applications, and Stretching DNA fail to load on both Firefox and Chrome. The option to select the sims appears, but the individual sims do not open.

![2020-04-01DecafOpticalTweezers](https://user-images.githubusercontent.com/54685448/78193275-608b8100-7437-11ea-9eec-383ea0724adb.gif)

**Comment by KatieWoe** [comment] 2020-04-02 20:30
Likely same as https://github.com/phetsims/decaf/issues/9

**Comment by loganbraywork** [comment] 2020-04-02 21:13
Below is the console log and error for this sim on Firefox:

CheerpJ is initializing loader.js:2838:11
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:95
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
unreachable code after return statement loader.js:4:183
unreachable code after return statement loader.js:4:741
Reporting error: Script error. loader.js:3054:10
ReferenceError: _c4pbM_8nG1uocdGbrnTidabrkDjsqD9ueqJuHteZMONn is not defined rt.jar.sun.awt.image.js:466:4061
    _c4pbM_8nG1uocdGbrnTidabr2CjsGEbYYerKxnn https://cjrtnc.leaningtech.com/2.1/runtime/rt.jar.sun.awt.image.js:466
    _h4V53awt5image17AffineTransformOp6filterE3 https://cjrtnc.leaningtech.com/2.1/runtime/rt.jar.java.awt.image.js:62
    _c4V_3edu8colorado4phet15opticaltweezers4view13LaserBeamNode27creatytycCL6yrebgbmGq0mjYayq4Dd https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.3/optical-tweezers_all.jar.js:3721
    _c4_$3edu8colorado4phet15opticaltweezers4view13LaserBeamNodeC2E0 https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.3/optical-tweezers_all.jar.js:3725
    anonymous https://cjrtnc.leaningtech.com/2.1/loader.js line 115 > Function:3
    runContinuationStack https://cjrtnc.leaningtech.com/2.1/loader.js:387
    cheerpjSchedule https://cjrtnc.leaningtech.com/2.1/loader.js:1110
    classLoadComplete https://cjrtnc.leaningtech.com/2.1/loader.js:167
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.google.com/forms/d/e/1FAIpQLScErDRKZvSy1JAdiRSZfAsjf711VWdSdkczuSYHfIHQbtyFXA/formResponse. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by samreid** [comment] 2020-04-06 14:41
It looks like this is caused by AffineTransformOp, let's track it in #9, closing.

**Closed by samreid** 2020-04-06 14:41 UTC
Labels: type:bug
